services:
  - type: web
    name: buyukhayot-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMINS
        sync: false
      - key: WEBAPP_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
